# Generated by Django 5.0.4 on 2024-04-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.PositiveSmallIntegerField()),
                ('taxmin_narx', models.PositiveIntegerField()),
                ('sana', models.DateTimeField(auto_now=True)),
                ('club1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esilar', to='mainApp.club')),
                ('club2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yangilar', to='mainApp.club')),
                ('mavsum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.mavsum')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.player')),
            ],
        ),
    ]
